apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  org: wanja.org
  app.kubernetes.io/part-of: person-service-knative

resources:
- postgres.yaml
- knative-service.yaml
- post-sync-hook.yaml
