#namePrefix: stage-  
commonLabels:
  variant: stage


# in stage we have 2 replicas
replicas:
- count: 2
  name: person-service

# replace the image tag of the container with stage
images:
- digest: sha256:ac61c247578acbe30d1348bbed9442d753eb70bb8533638719c50e78143baa0c
  name: quay.io/wpernath/person-service:latest
  newName: quay.io/wpernath/person-service:v0.5.1

# generate a configmap 
configMapGenerator:
- literals:
  - APP_GREETING=We are in STAGING mode
  name: app-config

# apply some patches
  # apply health checks to deployment

# This patch provides the name of the namespace into the env-value of the Job
# This is needed because we want to call the target rest service of person-service
# which is: person-service.$NAMESPACE.svc:8080
#- path: apply-health-checks.yaml
#  target:
#    kind: Deployment
#    name: person-service
#    version: v1
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: book-stage
  target:
    kind: Job
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
